//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

using CiTest.Entities;

namespace CiTest {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://creditinfo.com/schemas/Sample/Data")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://creditinfo.com/schemas/Sample/Data", IsNullable=false)]
    public partial class Batch {
        
        private Contract[] contractField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Contract")]
        public Contract[] Contract {
            get {
                return this.contractField;
            }
            set {
                this.contractField = value;
            }
        }
    }
}
